Update action.yml

diff --git a/docker-deploy-action/action.yml b/docker-deploy-action/action.yml
--- a/docker-deploy-action/action.yml
+++ b/docker-deploy-action/action.yml
@@ -30,14 +30,33 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - run: bash deploy-script.sh
+    - name: Setup SSH Key
       shell: bash
-      env:
-        REGISTRY: ${{ inputs.registry }}
-        IMAGE_NAME: ${{ inputs.image_name }}
-        SERVICE_NAME: ${{ inputs.service_name }}
-        INTERNAL_PORT: ${{ inputs.internal_port }}
-        EXTERNAL_PORT: ${{ inputs.external_port }}
-        SERVER_USER: ${{ inputs.server_user }}
-        SERVER_HOST: ${{ inputs.server_host }}
-        SERVER_SSH_PRIVATE_KEY: ${{ inputs.server_ssh_private_key }}
+      run: |
+        mkdir -p ~/.ssh
+        echo "${{ inputs.server_ssh_private_key }}" | base64 --decode > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        ssh-keyscan -H ${{ inputs.server_host }} >> ~/.ssh/known_hosts
+
+    - name: Login to Docker Registry
+      shell: bash
+      run: |
+        echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ inputs.registry }} -u ${{ github.actor }} --password-stdin
+
+    - name: Pull Docker Image
+      shell: bash
+      run: |
+        docker pull ${{ inputs.registry }}/${{ inputs.image_name }}:${{ github.run_id }}
+
+    - name: Remove old Docker service
+      shell: bash
+      run: |
+        ssh -i ~/.ssh/id_rsa ${{ inputs.server_user }}@${{ inputs.server_host }} \
+        "docker service rm ${{ inputs.service_name }} || echo 'Service not found. Removing any old services.'"
+
+    - name: Deploy Docker image as a service
+      shell: bash
+      run: |
+        ssh -i ~/.ssh/id_rsa ${{ inputs.server_user }}@${{ inputs.server_host }} \
+        "docker service create --name ${{ inputs.service_name }} --publish published=${{ inputs.external_port }},target=${{ inputs.internal_port }} --replicas 1 ${{
+        inputs.registry }}/${{ inputs.image_name }}:${{ github.run_id }}"
